name = "falconhoof"
main = "src/index.ts"
compatibility_date = "2025-10-01"

routes = [
  { pattern = "falconhoof.clydeford.net", custom_domain = true }
]

[ai]
binding = "AI"

[observability]
enabled = true
